// <auto-generated />
namespace FCL.Cockerham.Ogsm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170518ActionPlanIntegrateWithPiller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170518ActionPlanIntegrateWithPiller));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181002357_2017-05-18-ActionPlan-Integrate-With-Piller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
