// <auto-generated />
namespace FCL.Cockerham.Ogsm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170505ExcelChangesAppended : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170505ExcelChangesAppended));
        
        string IMigrationMetadata.Id
        {
            get { return "201705050831276_2017-05-05-ExcelChangesAppended"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
