// <auto-generated />
namespace FCL.Cockerham.Ogsm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170512StTypeIntegrateWithBusinessUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170512StTypeIntegrateWithBusinessUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "201705120648299_2017-05-12-StType-Integrate-With-BusinessUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
