//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCL.Web.Framework.Core.RazorExtentions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplateEditorScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateEditorScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FCL.Web.Framework.Core.RazorExtentions.TemplateEditorScript", typeof(TemplateEditorScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;$(document).ready(function() {{ $(&apos;#{0}&apos;).summernote({{ 
        ///    width:{1},
        ///    height:{2},
        ///    minHeight: {3},
        ///    maxHeight: {4},
        ///    templateEditor:{5},
        ///    parserRegEx:&quot;{6}&quot;,
        ///    focus: true,
        ///    toolbar: [
        ///        [&apos;style&apos;, [&apos;bold&apos;, &apos;italic&apos;, &apos;underline&apos;, &apos;clear&apos;]],
        ///        [&apos;font&apos;, [&apos;strikethrough&apos;, &apos;superscript&apos;, &apos;subscript&apos;]],
        ///        [&apos;fontsize&apos;, [&apos;fontsize&apos;]],
        ///        [&apos;color&apos;, [&apos;color&apos;]],
        ///        [&apos;para&apos;, [&apos;ul&apos;, &apos;ol&apos;, &apos;paragraph&apos;]],
        ///        [&apos;template&apos;, [&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_editor {
            get {
                return ResourceManager.GetString("template_editor", resourceCulture);
            }
        }
    }
}
